### ISSUE TITLE
about the pre-trained model

### ISSUE THREAD

**Issue by shawnthu** [ilaria-manco/music-audio-tagging-pytorch#5]
hi, have u ever checked this repo: https://github.com/jordipons/musicnn
I wanna know that u trained this model from scratch, or converted original tensorflow checkpoint to pytorch pt?

**Comment by ilaria-manco** [comment]
Hi @shawnthu, yes, that's the official repo with the models trained using the original Tensorflow implementation (https://github.com/jordipons/musicnn-training). 

The pre-trained model in my repo was trained from scratch using this PyTorch implementation, not ported from Tensorflow, hence the results may vary slightly. Hope this helps!

**Comment by shawnthu** [comment]
> Hi @shawnthu, yes, that's the official repo with the models trained using the original Tensorflow implementation (https://github.com/jordipons/musicnn-training).
> 
> The pre-trained model in my repo was trained from scratch using this PyTorch implementation, not ported from Tensorflow, hence the results may vary slightly. Hope this helps!

got u, thx
